#include "Arc.h"

namespace shared {




Arc::Arc()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:00000000000009A7 begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:00000000000009A7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace shared */
