#include "Elementary.h"

namespace shared {




Elementary::Elementary()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-706d4881:1533916750f:-8000:0000000000000B7F begin
{
}
// section -64--88-56-1-706d4881:1533916750f:-8000:0000000000000B7F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace shared */
