#include "Message.h"

namespace shared {




void Message::add(Message toConcatenate)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-706d4881:1533916750f:-8000:0000000000000B7A begin
{
}
// section -64--88-56-1-706d4881:1533916750f:-8000:0000000000000B7A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Message::Message()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-706d4881:1533916750f:-8000:0000000000000B7D begin
{
}
// section -64--88-56-1-706d4881:1533916750f:-8000:0000000000000B7D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Constraint Message::selectConstraint(Constraint theConstraint)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--5f1ea4a7:1533e5553de:-8000:0000000000000BB8 begin
{
}
// section -64--88-56-1--5f1ea4a7:1533e5553de:-8000:0000000000000BB8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace shared */
