#include "Point.h"

namespace shared {




Point::Point()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--10a4e5b1:1533e138e73:-8000:0000000000000B86 begin
{
}
// section -64--88-56-1--10a4e5b1:1533e138e73:-8000:0000000000000B86 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace shared */
