#include "Shaper12.h"

namespace recognizer {




Boolean Shaper12::matcher(shared::SimpleShapeTODO )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:0000000000000921 begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:0000000000000921 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Shaper12::leMatcheur()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:0000000000000940 begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:0000000000000940 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Shaper12::recevoir()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:000000000000094D begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:000000000000094D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Shaper12::envoyer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:000000000000095B begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:000000000000095B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Shaper12::Shaper12()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:00000000000009AD begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:00000000000009AD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace recognizer */
