#include "Shaper23.h"

namespace recognizer {




Boolean Shaper23::matcher(Integer )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:0000000000000958 begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:0000000000000958 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Shaper23::leMatcheur()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:000000000000095D begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:000000000000095D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Shaper23::Shaper23()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:00000000000009B1 begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:00000000000009B1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace recognizer */
