#include "APICatalogueur.h"

namespace API {




void APICatalogueur::miseAJourFS(String fichierTexteFS)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:000000000000099D begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:000000000000099D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void APICatalogueur::miseAJourFC(String fichierTexteFC)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:000000000000099F begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:000000000000099F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

APICatalogueur::APICatalogueur()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:00000000000009BD begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:00000000000009BD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace API */
