#include "APItri.h"

namespace API {

/*
 */



void APItri::gatherSegment()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:000000000000086C begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:000000000000086C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void APItri::gatherCercle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:0000000000000914 begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:0000000000000914 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void APItri::recevoir()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:0000000000000949 begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:0000000000000949 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void APItri::envoyer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:000000000000094B begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:000000000000094B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

APItri::APItri()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--1ac85957:1532814bc75:-8000:00000000000009BF begin
{
}
// section -64--88-56-1--1ac85957:1532814bc75:-8000:00000000000009BF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace API */
